name: Build and Deploy .NET App to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'mywebapp1'    
  DOTNET_VERSION: '10.0.x'         

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}


    - name: Build Application
      run: dotnet build --configuration Release

    - name: Publish Application
      run: dotnet publish -c Release -o ${{ runner.temp }}/output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ runner.temp }}/output
